name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: TryHackMe Badge Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "Kumpel7"
          GITHUB_TOKEN: ${{secrets.TOKENTOKEN}}
